#!/bin/bash

cd /home/ec2-user/

# Install dotnet core
rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
yum -y update
yum -y install dotnet-sdk-3.1
chmod 777 -R /home/ec2-user/aspnetcoreservice/wwwroot/ffmpeg

# First time running dotnet tool requires setting up package cache
dotnet nuget
